#define PRODUCT_VERSION_MAJOR 1
#define PRODUCT_VERSION_MINOR 0
#define PRODUCT_VERSION_PATCH 0
#define PRODUCT_VERSION_RELEASE 0
#define COMMIT_ID ""
#define LEGAL_COPY_RIGHT  "Copyright (C) 2022 Huya"

#define _STR(R)  #R
#define STR(R) _STR(R)

#define STR_PRODUCT_VERSION STR(PRODUCT_VERSION_MAJOR) "." STR(PRODUCT_VERSION_MINOR) "." STR(PRODUCT_VERSION_PATCH) "." STR(PRODUCT_VERSION_RELEASE)

#define PRODUCT_INFO LEGAL_COPY_RIGHT "\nVersion:" STR_PRODUCT_VERSION "\nCommit id:" COMMIT_ID